### ISSUE TITLE
The "bootstrap" command was removed by default in v7, and is no longer maintained

### ISSUE THREAD

**Issue by chiragpurohit71085** [filoxo/single-spa-example-rxjs-shared-state#9]
Node version: v18.18.0
NPM version : 9.8.1
Reference: https://futurestud.io/tutorials/lerna-replacing-the-bootstrap-command
`yarn bootstrap
yarn run v1.22.19
$ lerna bootstrap
ERR! bootstrap The "bootstrap" command was removed by default in v7, and is no longer maintained.
ERR! bootstrap Learn more about this change at https://lerna.js.org/docs/legacy-package-management
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by filoxo** [comment]
I'd like to migrate to Nx at some point in the future.
